### ISSUE TITLE
Feature Request: Alphabetize variables in the debugger 

### ISSUE THREAD

**Issue by ZeWaka** [willox/auxtools#14]
It's quite annoying searching for variables currently, having to scroll through potentially hundreds of variables to find the one you're looking for.
It looks like it's currently grouped by inheritance from the type, but that doesn't really help when you're debugging `mob/carbon/human` or something and trying to find a `mob/`-scope var.
Even then, it's not even alphabetized within the type scope:
![Code_2020-12-19_10-39-01](https://user-images.githubusercontent.com/4741640/102696869-da92ae80-41ee-11eb-8189-a497ac8e4621.png)

**Comment by SpaceManiac** [comment]
My preference would be:
- `type` always on top if present
- remaining variables alphabetized case-insensitively
