### ISSUE TITLE
1616 sigs don't work

### ISSUE THREAD

**Issue by vvvv-vvvv** [willox/auxtools#78]
On Windows:

> Welcome BYOND! (5.0 Beta Version 515.1616)
> auxtools_init: FAILED (FAILED (Couldn't find execute_instruction))

**Comment by ZeWaka** [comment]
@Absolucy

**Comment by itsmeow** [comment]
Yeah we encountered this randomly as well. It only happened later into rounds though so I'm not sure what sig is responsible
